'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ms';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.overview': 'Overview',
    'nav.forecast': 'Forecast',
    'nav.statistics': 'Statistics',
    'nav.report': 'Report',
    'nav.faq': 'FAQ',
    
    // Homepage
    'home.badge': 'AI-Powered Prediction System',
    'home.title1': 'From Aid to',
    'home.title2': 'Independence',
    'home.subtitle': 'Predicting poverty escape likelihood for zakat recipients in Kedah using advanced machine learning, helping institutions make data-driven decisions for effective resource allocation.',
    'home.cta.predict': 'Start Prediction',
    'home.cta.learn': 'Learn More',
    'home.stats.recipients': 'Total Recipients',
    'home.stats.accuracy': 'Model Accuracy',
    'home.stats.features': 'Features Analyzed',
    'home.stats.districts': 'Districts Covered',
    'home.features.title': 'Explore Our Features',
    'home.features.subtitle': 'Comprehensive tools for poverty analysis and prediction',
    'home.features.overview': 'Overview',
    'home.features.overview.desc': 'Interactive dashboard with district maps and key insights',
    'home.features.forecast': 'Forecast',
    'home.features.forecast.desc': 'AI-powered poverty escape prediction with recommendations',
    'home.features.statistics': 'Statistics',
    'home.features.statistics.desc': 'Detailed demographic and financial analysis',
    'home.features.report': 'Report',
    'home.features.report.desc': 'Comprehensive research findings and methodology',

    // About Page
    'about.badge': 'Research Project',
    'about.title': 'About',
    'about.title2': 'This Project',
    'about.subtitle': 'Understanding the methodology and research behind the P2P Zakat Poverty Escape Prediction System',
    'about.research.title': 'Research Background',
    'about.research.desc': 'This project was developed to assist Lembaga Zakat Negeri Kedah (LZNK) in predicting the likelihood of zakat recipients (asnaf) escaping poverty. By leveraging machine learning techniques, we aim to provide data-driven insights for more effective resource allocation.',
    'about.methodology.title': 'Methodology',
    'about.methodology.desc': 'Our approach combines extensive data analysis with advanced machine learning algorithms. We analyzed data from 51,962 zakat recipients across 12 districts in Kedah, examining 113 different features to build our prediction model.',
    'about.model.title': 'Model Performance',
    'about.model.accuracy': 'Accuracy',
    'about.model.roc': 'ROC-AUC Score',
    'about.model.precision': 'Precision',
    'about.model.recall': 'Recall',
    'about.team.title': 'Research Team',
    'about.team.subtitle': 'Meet the researchers behind this project',
    'about.objectives.title': 'Research Objectives',
    'about.objectives.1': 'Identify key factors influencing poverty escape',
    'about.objectives.2': 'Build accurate prediction models using ML',
    'about.objectives.3': 'Provide actionable insights for zakat institutions',
    'about.objectives.4': 'Support evidence-based policy making',

    // Overview Page
    'overview.badge': 'Dashboard',
    'overview.title': 'Zakat Recipients',
    'overview.title2': 'Overview',
    'overview.subtitle': 'Comprehensive analysis of 51,962 zakat recipients across Kedah',
    'overview.map.title': 'Kedah Districts',
    'overview.map.subtitle': 'Geographic distribution of recipients',
    'overview.quickstats': 'Quick Statistics',
    'overview.demographics': 'Demographics',
    'overview.financial': 'Financial Overview',
    'overview.employment': 'Employment Status',
    'overview.avgIncome': 'Average Income',
    'overview.avgExpense': 'Average Expense',
    'overview.monthlyGap': 'Monthly Gap',

    // Forecast Page
    'forecast.badge': 'AI Prediction',
    'forecast.title': 'Poverty Escape',
    'forecast.title2': 'Predictor',
    'forecast.subtitle': 'Enter recipient details to predict likelihood of escaping poverty',
    'forecast.input.title': 'Recipient Information',
    'forecast.input.income': 'Monthly Income (RM)',
    'forecast.input.expense': 'Monthly Expense (RM)',
    'forecast.input.dependents': 'Number of Dependents',
    'forecast.input.age': 'Age',
    'forecast.input.health': 'Health Status',
    'forecast.input.education': 'Education Level',
    'forecast.input.employment': 'Employment Status',
    'forecast.input.health.good': 'Good',
    'forecast.input.health.moderate': 'Moderate',
    'forecast.input.health.poor': 'Poor',
    'forecast.input.edu.none': 'No Formal Education',
    'forecast.input.edu.primary': 'Primary School',
    'forecast.input.edu.secondary': 'Secondary School',
    'forecast.input.edu.tertiary': 'Tertiary Education',
    'forecast.input.emp.unemployed': 'Unemployed',
    'forecast.input.emp.selfEmployed': 'Self-Employed',
    'forecast.input.emp.private': 'Private Sector',
    'forecast.input.emp.government': 'Government',
    'forecast.btn.predict': 'Predict',
    'forecast.btn.reset': 'Reset',
    'forecast.result.title': 'Prediction Result',
    'forecast.result.probability': 'Escape Probability',
    'forecast.result.confidence': 'Confidence Level',
    'forecast.result.confidence.high': 'High',
    'forecast.result.confidence.moderate': 'Moderate',
    'forecast.result.confidence.low': 'Low',
    'forecast.result.recommendation': 'Recommendations',
    'forecast.result.timeline': '3-Year Forecast',
    'forecast.result.year': 'Year',

    // Statistics Page
    'stats.badge': 'Data Analysis',
    'stats.title': 'Recipient',
    'stats.title2': 'Statistics',
    'stats.subtitle': 'Detailed statistical analysis of zakat recipients in Kedah',
    'stats.district.title': 'Distribution by District',
    'stats.income.title': 'Income Distribution',
    'stats.age.title': 'Age Distribution',
    'stats.employment.title': 'Employment Status',
    'stats.health.title': 'Health Status',
    'stats.education.title': 'Education Level',

    // Report Page
    'report.badge': 'Research Findings',
    'report.title': 'Comprehensive',
    'report.title2': 'Report',
    'report.subtitle': 'Detailed analysis and findings from the zakat recipient study',
    'report.summary.title': 'Executive Summary',
    'report.findings.title': 'Key Findings',
    'report.recommendations.title': 'Recommendations',
    'report.conclusion.title': 'Conclusion',

    // FAQ Page
    'faq.badge': 'Help Center',
    'faq.title': 'Frequently Asked',
    'faq.title2': 'Questions',
    'faq.subtitle': 'Find answers to common questions about the P2P Zakat Poverty Escape Prediction System',
    'faq.search': 'Search questions...',
    'faq.showing': 'Showing',
    'faq.of': 'of',
    'faq.questions': 'questions',
    'faq.noResults': 'No results found',
    'faq.noResults.desc': 'Try adjusting your search or filter criteria',
    'faq.contact.title': 'Still have questions?',
    'faq.contact.desc': "Can't find the answer you're looking for? Feel free to reach out to our developer.",
    'faq.contact.btn': 'Contact Support',
    'faq.contact.learn': 'Learn More',
    'faq.cat.all': 'All',
    'faq.cat.general': 'General',
    'faq.cat.model': 'Prediction Model',
    'faq.cat.data': 'Data & Statistics',
    'faq.cat.usage': 'Using the System',
    'faq.cat.technical': 'Technical',
    'faq.stats.accuracy': 'Model Accuracy',
    'faq.stats.recipients': 'Recipients Analyzed',
    'faq.stats.features': 'Features Used',
    'faq.stats.districts': 'Districts Covered',
    // FAQ Q&A - General
    'faq.q1': 'What is the P2P Zakat Poverty Escape Prediction System?',
    'faq.a1': 'The P2P Zakat system is a machine learning-powered platform designed to predict the likelihood of zakat recipients (asnaf) escaping poverty. It uses data from 51,962 recipients in Kedah, Malaysia, and analyzes 113 socioeconomic features to provide actionable insights for zakat institutions.',
    'faq.q2': 'Who can use this system?',
    'faq.a2': 'This system is designed for zakat institutions, policymakers, researchers, and social welfare organizations. It helps them make data-driven decisions about resource allocation and intervention strategies for poverty alleviation.',
    'faq.q3': 'What data sources are used?',
    'faq.a3': 'The system uses official data from Lembaga Zakat Negeri Kedah (LZNK) collected between 2022-2024. This includes demographic information, financial status, employment data, health records, and asset ownership details of zakat recipients.',
    // FAQ Q&A - Prediction Model
    'faq.q4': 'How accurate is the prediction model?',
    'faq.a4': 'Our Support Vector Machine (SVM) model achieves 94.73% accuracy with a ROC-AUC score of 98.96%. This means the model correctly identifies recipients who are likely to escape poverty vs. those who need continued support with high reliability.',
    'faq.q5': 'What factors influence the poverty escape prediction?',
    'faq.a5': 'The top factors include: Total Income (15.2% importance), Income-Expense Ratio (13.9%), Total Expenses (11.8%), Number of Dependents (10.4%), Job Type (8.7%), Age (7.6%), and Health Status (4.1%). These factors were identified through feature importance analysis.',
    'faq.q6': 'Why was SVM chosen over other models?',
    'faq.a6': 'SVM (Support Vector Machine) with RBF kernel was selected because it achieved the highest ROC-AUC score (98.96%) and best accuracy (94.73%) among all tested models. It also handles high-dimensional data well (113 features) and is robust against overfitting.',
    'faq.q7': 'What does the 3-year probability forecast mean?',
    'faq.a7': 'The 3-year forecast shows the cumulative probability of a recipient escaping poverty over time. Year 1 shows initial progress, Year 2 shows mid-term improvement, and Year 3 shows the full predicted probability based on all input factors.',
    // FAQ Q&A - Data & Statistics
    'faq.q8': 'How many recipients are in the dataset?',
    'faq.a8': 'The dataset contains 51,962 zakat recipients (asnaf) from all 12 districts in Kedah, Malaysia. Data was collected over 3 years (2022-2024) with an average of approximately 17,300 recipients per year.',
    'faq.q9': 'What is the average income and expense of recipients?',
    'faq.a9': 'The average monthly income is RM 763 while average monthly expenses are RM 942, resulting in a negative gap of RM 179 per month. This highlights the financial vulnerability of zakat recipients.',
    'faq.q10': 'What percentage of recipients are unemployed?',
    'faq.a10': '59.6% of zakat recipients are unemployed. Among the employed, 30% are self-employed, 7.9% work in the private sector, and only 0.3% work in government positions.',
    'faq.q11': 'Which districts have the most recipients?',
    'faq.a11': 'The top 3 districts are: Kuala Muda (8,275 recipients, 15.9%), Kota Setar (8,013 recipients, 15.4%), and Baling (7,462 recipients, 14.4%). These three districts account for nearly half of all recipients.',
    // FAQ Q&A - Using the System
    'faq.q12': 'How do I use the Poverty Predictor?',
    'faq.a12': "Navigate to the Forecast page, enter the recipient's information using the sliders and dropdowns (income, expenses, dependents, age, health, education, employment), then click 'Predict' to see the poverty escape probability and recommendations.",
    'faq.q13': 'What do the confidence levels mean?',
    'faq.a13': 'High Confidence means the prediction is based on clear patterns in the data. Moderate Confidence indicates a balanced case. Low Confidence suggests the recipient falls in an uncertain zone where outcomes are harder to predict.',
    'faq.q14': 'How should I interpret the recommendations?',
    'faq.a14': "Recommendations are generated based on the input factors. They suggest specific intervention programs such as income-generating activities, family support, skills training, job placement, or healthcare assistance based on the recipient's profile.",
    // FAQ Q&A - Technical
    'faq.q15': 'What machine learning algorithms were compared?',
    'faq.a15': 'We compared SVM (RBF Kernel), Neural Network (MLP), Logistic Regression, K-Nearest Neighbors, and Gaussian Naive Bayes. SVM was selected as the production model due to its superior performance and generalization ability.',
    'faq.q16': 'How many features are used in the model?',
    'faq.a16': '113 features are used, covering demographics (age, gender, marital status), financial status (income, expenses, savings), employment details, health conditions, asset ownership, and geographic location.',
    'faq.q17': 'Is the prediction model updated regularly?',
    'faq.a17': 'The model is designed to be retrained periodically as new data becomes available. This ensures the predictions remain accurate and reflect current socioeconomic conditions.',

    // Common
    'common.learnMore': 'Learn More',
    'common.viewDetails': 'View Details',
    'common.explore': 'Explore',
    'common.recipients': 'Recipients',
    'common.percentage': 'Percentage',
    'common.district': 'District',
    'common.total': 'Total',
    'common.average': 'Average',
    'common.year': 'Year',
    'common.years': 'years',
    'common.total2': 'total',
    'common.projected': 'projected',
    'common.dataSource': 'Data Source',
    
    // Overview Page Additional
    'overview.recipients': 'Recipients',
    'overview.monthlyRecipients': 'Monthly Recipients',
    'overview.hoverDetails': 'Hover over bars to see details',
    'overview.districtMap': 'Kedah District Map',
    'overview.clickDistrict': 'Click on a district',
    'overview.interactiveMap': 'Interactive map showing recipient distribution',
    'overview.viewDetails': 'to view details',
    'overview.avgIncome2': 'Avg Income',
    'overview.avgExpense2': 'Avg Expense',
    'overview.unemployedRate': 'Unemployed Rate',
    'overview.gap': 'Gap',
    'overview.month': 'month',
    'overview.lowDensity': 'Low Density',
    'overview.highDensity': 'High Density',
    
    // Statistics Page Additional
    'stats.recipientsByDistrict': 'Recipients by District',
    'stats.clickBar': 'Click on a bar to view details',
    'stats.distributionShare': 'Distribution Share',
    'stats.top6Districts': 'Top 6 districts',
    'stats.districts': 'Districts',
    'stats.ageDistribution': 'Age Distribution',
    'stats.recipientsByAge': 'Recipients by age group',
    'stats.demographicInsights': 'Demographic Insights',
    'stats.female': 'Female',
    'stats.male': 'Male',
    'stats.married': 'Married',
    'stats.healthy': 'Healthy',
    'stats.averageAge': 'Average Age',
    'stats.topDistrict': 'Top District',
    
    // Forecast Page Additional
    'forecast.generalForecast': 'General Multi-Year Forecast',
    'forecast.consolidatedProjections': 'Consolidated poverty escape projections (2022-2027)',
    'forecast.totalRecipients': 'Total Recipients',
    'forecast.avgRecipientsYear': 'Avg Recipients/Year',
    'forecast.escapeRate': 'Escape Rate',
    'forecast.escapeRateTrend': 'Escape Rate Trend',
    'forecast.actual': 'Actual',
    'forecast.forecastLabel': 'Forecast',
    'forecast.growth': 'Growth',
    'forecast.currentRate': 'Current Rate',
    'forecast.target': 'Target',
    'forecast.projectedGrowth': 'Projected Growth',
    'forecast.improvingTrend': 'Improving Trend',
    'forecast.improvingDesc': 'Escape rate increased from 12.3% (2022) to 16.2% (2024), a 31.7% improvement',
    'forecast.threeYearProjection': '3-Year Projection',
    'forecast.projectionDesc': 'Model predicts escape rate to reach 24% by 2027 with current intervention strategies',
    'forecast.recipientInfo': 'Recipient Information',
    
    // Report Page Additional
    'report.healthStatus': 'Health Status',
    'report.recipientsByHealth': 'Recipients by health condition',
    'report.maritalStatus': 'Marital Status',
    'report.distributionByFamily': 'Distribution by family status',
    'report.employmentStatus': 'Employment Status',
    'report.monthlyExpenses': 'Monthly Expenses',
    'report.housingType': 'Housing Type',
    'report.basedOnHouse': 'Based on house structure type (Batu/Kayu)',
    'report.recipientsByYear': 'Recipients by Year',
    'report.annualDistribution': 'Annual distribution (2022-2024)',
    'report.avgYear': 'Avg/Year',
    'report.assetOwnership': 'Asset Ownership',
    'report.householdItems': 'Household items owned by recipients',

    // About Page Additional
    'about.researchOverview': 'Research Overview',
    'about.understandingScope': 'Understanding the project scope and objectives',
    'about.modelPerformance': 'Model Performance',
    'about.comparingAlgorithms': 'Comparing machine learning algorithms',
    'about.selectedModel': 'Selected Model',
    'about.whySVM': 'Why SVM was Selected',
    'about.keyFeatures': 'Key Features Analyzed',
    'about.socioeconomicIndicators': '113 socioeconomic indicators across 6 categories',
    'about.methodologyTitle': 'Methodology',
    'about.ourProcess': 'Our research process step by step',
    'about.dataCollected': 'Data Collected',
    'about.officialRecords': 'Official zakat recipient records from 2022-2024',
    'about.researchDesc1': 'This project develops a',
    'about.mlModel': 'machine learning-based predictive model',
    'about.researchDesc2': 'to assess the probability of zakat recipients escaping poverty. Using comprehensive data from',
    'about.asnaf': '(zakat recipients)',
    'about.researchDesc3': 'in Kedah, Malaysia collected between 2022-2024, we analyze',
    'about.researchDesc4': 'to predict escape potential within a 3-year horizon.',
    'about.researchDesc5': 'The model enables zakat institutions to',
    'about.optimizeResource': 'optimize resource allocation',
    'about.researchDesc6': 'and develop',
    'about.targetedIntervention': 'targeted intervention strategies',
    'about.researchDesc7': 'tailored to different recipient profiles, maximizing the social impact of zakat distribution.',
    'about.svm1.title': 'Highest ROC-AUC (98.96%)',
    'about.svm1.desc': 'Superior ability to distinguish between recipients who can escape poverty vs. those who cannot.',
    'about.svm2.title': 'Best Accuracy (94.73%)',
    'about.svm2.desc': 'Outperforms all other models in correctly classifying recipient outcomes.',
    'about.svm3.title': 'Handles High Dimensions',
    'about.svm3.desc': 'Effectively processes 113 features using RBF kernel for complex non-linear relationships.',
    'about.svm4.title': 'Robust to Overfitting',
    'about.svm4.desc': 'Margin-based optimization provides better generalization on unseen data.',
    'about.feat.demographics': 'Demographics',
    'about.feat.demographics.desc': 'Age, gender, marital status, dependents',
    'about.feat.financial': 'Financial Status',
    'about.feat.financial.desc': 'Income, expenses, savings, debts',
    'about.feat.employment': 'Employment',
    'about.feat.employment.desc': 'Job type, occupation sector, skills',
    'about.feat.health': 'Health',
    'about.feat.health.desc': 'Health status, disabilities, chronic illness',
    'about.feat.assets': 'Assets',
    'about.feat.assets.desc': 'Property, vehicles, appliances owned',
    'about.feat.geographic': 'Geographic',
    'about.feat.geographic.desc': 'District, urban/rural location',
    'about.method1.title': 'Data Collection',
    'about.method1.desc': 'Gathered comprehensive data from LZNK on 51,962 recipients across all 12 districts in Kedah state.',
    'about.method2.title': 'Feature Engineering',
    'about.method2.desc': 'Processed and engineered 113 features including income ratios, expense patterns, and risk indicators.',
    'about.method3.title': 'Model Training',
    'about.method3.desc': 'Compared multiple ML algorithms: Logistic Regression, Random Forest, SVM, and Gradient Boosting.',
    'about.method4.title': 'Validation',
    'about.method4.desc': 'Applied stratified k-fold cross-validation to ensure robust and reliable performance estimates.',

    // Home Page Additional
    'home.incomeVsExpense': 'Income vs Expenses Gap',
    'home.incomeVsExpense.desc': 'Average monthly financial situation of recipients',
    'home.income': 'Income',
    'home.expenses': 'Expenses',
    'home.gap': 'Gap',
  },
  ms: {
    // Navbar
    'nav.home': 'Utama',
    'nav.about': 'Tentang',
    'nav.overview': 'Gambaran',
    'nav.forecast': 'Ramalan',
    'nav.statistics': 'Statistik',
    'nav.report': 'Laporan',
    'nav.faq': 'FAQ',
    
    // Homepage
    'home.badge': 'Sistem Ramalan Berkuasa AI',
    'home.title1': 'Dari Bantuan ke',
    'home.title2': 'Kemerdekaan',
    'home.subtitle': 'Meramal kemungkinan penerima zakat di Kedah keluar dari kemiskinan menggunakan pembelajaran mesin, membantu institusi membuat keputusan berasaskan data untuk peruntukan sumber yang berkesan.',
    'home.cta.predict': 'Mula Ramalan',
    'home.cta.learn': 'Ketahui Lebih',
    'home.stats.recipients': 'Jumlah Penerima',
    'home.stats.accuracy': 'Ketepatan Model',
    'home.stats.features': 'Ciri Dianalisis',
    'home.stats.districts': 'Daerah Diliputi',
    'home.features.title': 'Terokai Ciri-ciri Kami',
    'home.features.subtitle': 'Alat komprehensif untuk analisis dan ramalan kemiskinan',
    'home.features.overview': 'Gambaran',
    'home.features.overview.desc': 'Papan pemuka interaktif dengan peta daerah dan pandangan utama',
    'home.features.forecast': 'Ramalan',
    'home.features.forecast.desc': 'Ramalan keluar kemiskinan berkuasa AI dengan cadangan',
    'home.features.statistics': 'Statistik',
    'home.features.statistics.desc': 'Analisis demografi dan kewangan terperinci',
    'home.features.report': 'Laporan',
    'home.features.report.desc': 'Penemuan penyelidikan dan metodologi komprehensif',

    // About Page
    'about.badge': 'Projek Penyelidikan',
    'about.title': 'Tentang',
    'about.title2': 'Projek Ini',
    'about.subtitle': 'Memahami metodologi dan penyelidikan di sebalik Sistem Ramalan Keluar Kemiskinan P2P Zakat',
    'about.research.title': 'Latar Belakang Penyelidikan',
    'about.research.desc': 'Projek ini dibangunkan untuk membantu Lembaga Zakat Negeri Kedah (LZNK) dalam meramal kemungkinan penerima zakat (asnaf) keluar dari kemiskinan. Dengan menggunakan teknik pembelajaran mesin, kami bertujuan memberikan pandangan berasaskan data untuk peruntukan sumber yang lebih berkesan.',
    'about.methodology.title': 'Metodologi',
    'about.methodology.desc': 'Pendekatan kami menggabungkan analisis data yang meluas dengan algoritma pembelajaran mesin canggih. Kami menganalisis data daripada 51,962 penerima zakat di 12 daerah di Kedah, mengkaji 113 ciri berbeza untuk membina model ramalan kami.',
    'about.model.title': 'Prestasi Model',
    'about.model.accuracy': 'Ketepatan',
    'about.model.roc': 'Skor ROC-AUC',
    'about.model.precision': 'Kejituan',
    'about.model.recall': 'Recall',
    'about.team.title': 'Pasukan Penyelidikan',
    'about.team.subtitle': 'Kenali penyelidik di sebalik projek ini',
    'about.objectives.title': 'Objektif Penyelidikan',
    'about.objectives.1': 'Mengenal pasti faktor utama yang mempengaruhi keluar kemiskinan',
    'about.objectives.2': 'Membina model ramalan tepat menggunakan ML',
    'about.objectives.3': 'Menyediakan pandangan boleh tindak untuk institusi zakat',
    'about.objectives.4': 'Menyokong pembuatan dasar berasaskan bukti',

    // Overview Page
    'overview.badge': 'Papan Pemuka',
    'overview.title': 'Gambaran Penerima',
    'overview.title2': 'Zakat',
    'overview.subtitle': 'Analisis komprehensif 51,962 penerima zakat di seluruh Kedah',
    'overview.map.title': 'Daerah Kedah',
    'overview.map.subtitle': 'Taburan geografi penerima',
    'overview.quickstats': 'Statistik Pantas',
    'overview.demographics': 'Demografi',
    'overview.financial': 'Gambaran Kewangan',
    'overview.employment': 'Status Pekerjaan',
    'overview.avgIncome': 'Purata Pendapatan',
    'overview.avgExpense': 'Purata Perbelanjaan',
    'overview.monthlyGap': 'Jurang Bulanan',

    // Forecast Page
    'forecast.badge': 'Ramalan AI',
    'forecast.title': 'Peramal Keluar',
    'forecast.title2': 'Kemiskinan',
    'forecast.subtitle': 'Masukkan butiran penerima untuk meramal kemungkinan keluar dari kemiskinan',
    'forecast.input.title': 'Maklumat Penerima',
    'forecast.input.income': 'Pendapatan Bulanan (RM)',
    'forecast.input.expense': 'Perbelanjaan Bulanan (RM)',
    'forecast.input.dependents': 'Bilangan Tanggungan',
    'forecast.input.age': 'Umur',
    'forecast.input.health': 'Status Kesihatan',
    'forecast.input.education': 'Tahap Pendidikan',
    'forecast.input.employment': 'Status Pekerjaan',
    'forecast.input.health.good': 'Baik',
    'forecast.input.health.moderate': 'Sederhana',
    'forecast.input.health.poor': 'Lemah',
    'forecast.input.edu.none': 'Tiada Pendidikan Formal',
    'forecast.input.edu.primary': 'Sekolah Rendah',
    'forecast.input.edu.secondary': 'Sekolah Menengah',
    'forecast.input.edu.tertiary': 'Pengajian Tinggi',
    'forecast.input.emp.unemployed': 'Tidak Bekerja',
    'forecast.input.emp.selfEmployed': 'Bekerja Sendiri',
    'forecast.input.emp.private': 'Sektor Swasta',
    'forecast.input.emp.government': 'Kerajaan',
    'forecast.btn.predict': 'Ramal',
    'forecast.btn.reset': 'Set Semula',
    'forecast.result.title': 'Hasil Ramalan',
    'forecast.result.probability': 'Kebarangkalian Keluar',
    'forecast.result.confidence': 'Tahap Keyakinan',
    'forecast.result.confidence.high': 'Tinggi',
    'forecast.result.confidence.moderate': 'Sederhana',
    'forecast.result.confidence.low': 'Rendah',
    'forecast.result.recommendation': 'Cadangan',
    'forecast.result.timeline': 'Ramalan 3 Tahun',
    'forecast.result.year': 'Tahun',

    // Statistics Page
    'stats.badge': 'Analisis Data',
    'stats.title': 'Statistik',
    'stats.title2': 'Penerima',
    'stats.subtitle': 'Analisis statistik terperinci penerima zakat di Kedah',
    'stats.district.title': 'Taburan Mengikut Daerah',
    'stats.income.title': 'Taburan Pendapatan',
    'stats.age.title': 'Taburan Umur',
    'stats.employment.title': 'Status Pekerjaan',
    'stats.health.title': 'Status Kesihatan',
    'stats.education.title': 'Tahap Pendidikan',

    // Report Page
    'report.badge': 'Penemuan Penyelidikan',
    'report.title': 'Laporan',
    'report.title2': 'Komprehensif',
    'report.subtitle': 'Analisis terperinci dan penemuan daripada kajian penerima zakat',
    'report.summary.title': 'Ringkasan Eksekutif',
    'report.findings.title': 'Penemuan Utama',
    'report.recommendations.title': 'Cadangan',
    'report.conclusion.title': 'Kesimpulan',

    // FAQ Page
    'faq.badge': 'Pusat Bantuan',
    'faq.title': 'Soalan Lazim',
    'faq.title2': 'Ditanya',
    'faq.subtitle': 'Cari jawapan kepada soalan lazim tentang Sistem Ramalan Keluar Kemiskinan P2P Zakat',
    'faq.search': 'Cari soalan...',
    'faq.showing': 'Menunjukkan',
    'faq.of': 'daripada',
    'faq.questions': 'soalan',
    'faq.noResults': 'Tiada hasil dijumpai',
    'faq.noResults.desc': 'Cuba laraskan carian atau kriteria penapis anda',
    'faq.contact.title': 'Masih ada soalan?',
    'faq.contact.desc': 'Tidak dapat mencari jawapan yang anda cari? Hubungi pembangun kami.',
    'faq.contact.btn': 'Hubungi Sokongan',
    'faq.contact.learn': 'Ketahui Lebih',
    'faq.cat.all': 'Semua',
    'faq.cat.general': 'Umum',
    'faq.cat.model': 'Model Ramalan',
    'faq.cat.data': 'Data & Statistik',
    'faq.cat.usage': 'Penggunaan Sistem',
    'faq.cat.technical': 'Teknikal',
    'faq.stats.accuracy': 'Ketepatan Model',
    'faq.stats.recipients': 'Penerima Dianalisis',
    'faq.stats.features': 'Ciri Digunakan',
    'faq.stats.districts': 'Daerah Diliputi',
    // FAQ Q&A - Umum
    'faq.q1': 'Apakah Sistem Ramalan Keluar Kemiskinan Zakat P2P?',
    'faq.a1': 'Sistem Zakat P2P adalah platform berkuasa pembelajaran mesin yang direka untuk meramalkan kebarangkalian penerima zakat (asnaf) keluar daripada kemiskinan. Ia menggunakan data daripada 51,962 penerima di Kedah, Malaysia, dan menganalisis 113 ciri sosioekonomi untuk memberikan pandangan yang boleh diambil tindakan kepada institusi zakat.',
    'faq.q2': 'Siapa yang boleh menggunakan sistem ini?',
    'faq.a2': 'Sistem ini direka untuk institusi zakat, pembuat dasar, penyelidik, dan organisasi kebajikan sosial. Ia membantu mereka membuat keputusan berasaskan data tentang peruntukan sumber dan strategi intervensi untuk pembasmian kemiskinan.',
    'faq.q3': 'Apakah sumber data yang digunakan?',
    'faq.a3': 'Sistem ini menggunakan data rasmi daripada Lembaga Zakat Negeri Kedah (LZNK) yang dikumpul antara 2022-2024. Ini termasuk maklumat demografi, status kewangan, data pekerjaan, rekod kesihatan, dan butiran pemilikan aset penerima zakat.',
    // FAQ Q&A - Model Ramalan
    'faq.q4': 'Sejauh mana ketepatan model ramalan?',
    'faq.a4': 'Model Support Vector Machine (SVM) kami mencapai ketepatan 94.73% dengan skor ROC-AUC 98.96%. Ini bermakna model dengan tepat mengenal pasti penerima yang berkemungkinan keluar daripada kemiskinan berbanding mereka yang memerlukan sokongan berterusan dengan kebolehpercayaan tinggi.',
    'faq.q5': 'Apakah faktor yang mempengaruhi ramalan keluar kemiskinan?',
    'faq.a5': 'Faktor utama termasuk: Jumlah Pendapatan (15.2% kepentingan), Nisbah Pendapatan-Perbelanjaan (13.9%), Jumlah Perbelanjaan (11.8%), Bilangan Tanggungan (10.4%), Jenis Pekerjaan (8.7%), Umur (7.6%), dan Status Kesihatan (4.1%). Faktor-faktor ini dikenal pasti melalui analisis kepentingan ciri.',
    'faq.q6': 'Mengapa SVM dipilih berbanding model lain?',
    'faq.a6': 'SVM (Support Vector Machine) dengan kernel RBF dipilih kerana ia mencapai skor ROC-AUC tertinggi (98.96%) dan ketepatan terbaik (94.73%) antara semua model yang diuji. Ia juga mengendalikan data berdimensi tinggi dengan baik (113 ciri) dan tahan terhadap overfitting.',
    'faq.q7': 'Apakah maksud ramalan kebarangkalian 3 tahun?',
    'faq.a7': 'Ramalan 3 tahun menunjukkan kebarangkalian kumulatif penerima keluar daripada kemiskinan dari masa ke masa. Tahun 1 menunjukkan kemajuan awal, Tahun 2 menunjukkan peningkatan jangka sederhana, dan Tahun 3 menunjukkan kebarangkalian penuh yang diramalkan berdasarkan semua faktor input.',
    // FAQ Q&A - Data & Statistik
    'faq.q8': 'Berapa ramai penerima dalam set data?',
    'faq.a8': 'Set data mengandungi 51,962 penerima zakat (asnaf) dari semua 12 daerah di Kedah, Malaysia. Data dikumpul selama 3 tahun (2022-2024) dengan purata kira-kira 17,300 penerima setahun.',
    'faq.q9': 'Apakah purata pendapatan dan perbelanjaan penerima?',
    'faq.a9': 'Purata pendapatan bulanan adalah RM 763 manakala purata perbelanjaan bulanan adalah RM 942, menghasilkan jurang negatif RM 179 sebulan. Ini menunjukkan kerentanan kewangan penerima zakat.',
    'faq.q10': 'Berapa peratus penerima yang menganggur?',
    'faq.a10': '59.6% penerima zakat adalah menganggur. Antara yang bekerja, 30% adalah bekerja sendiri, 7.9% bekerja di sektor swasta, dan hanya 0.3% bekerja di jawatan kerajaan.',
    'faq.q11': 'Daerah mana yang mempunyai paling ramai penerima?',
    'faq.a11': '3 daerah teratas adalah: Kuala Muda (8,275 penerima, 15.9%), Kota Setar (8,013 penerima, 15.4%), dan Baling (7,462 penerima, 14.4%). Tiga daerah ini menyumbang hampir separuh daripada semua penerima.',
    // FAQ Q&A - Penggunaan Sistem
    'faq.q12': 'Bagaimana saya menggunakan Peramal Kemiskinan?',
    'faq.a12': "Navigasi ke halaman Ramalan, masukkan maklumat penerima menggunakan peluncur dan dropdown (pendapatan, perbelanjaan, tanggungan, umur, kesihatan, pendidikan, pekerjaan), kemudian klik 'Ramal' untuk melihat kebarangkalian keluar kemiskinan dan cadangan.",
    'faq.q13': 'Apakah maksud tahap keyakinan?',
    'faq.a13': 'Keyakinan Tinggi bermakna ramalan berdasarkan corak yang jelas dalam data. Keyakinan Sederhana menunjukkan kes seimbang. Keyakinan Rendah mencadangkan penerima berada dalam zon tidak pasti di mana keputusan lebih sukar untuk diramalkan.',
    'faq.q14': 'Bagaimana saya harus mentafsir cadangan?',
    'faq.a14': 'Cadangan dijana berdasarkan faktor input. Ia mencadangkan program intervensi khusus seperti aktiviti menjana pendapatan, sokongan keluarga, latihan kemahiran, penempatan kerja, atau bantuan penjagaan kesihatan berdasarkan profil penerima.',
    // FAQ Q&A - Teknikal
    'faq.q15': 'Apakah algoritma pembelajaran mesin yang dibandingkan?',
    'faq.a15': 'Kami membandingkan SVM (Kernel RBF), Neural Network (MLP), Logistic Regression, K-Nearest Neighbors, dan Gaussian Naive Bayes. SVM dipilih sebagai model pengeluaran kerana prestasi unggul dan keupayaan generalisasinya.',
    'faq.q16': 'Berapa banyak ciri yang digunakan dalam model?',
    'faq.a16': '113 ciri digunakan, meliputi demografi (umur, jantina, status perkahwinan), status kewangan (pendapatan, perbelanjaan, simpanan), butiran pekerjaan, keadaan kesihatan, pemilikan aset, dan lokasi geografi.',
    'faq.q17': 'Adakah model ramalan dikemas kini secara berkala?',
    'faq.a17': 'Model ini direka untuk dilatih semula secara berkala apabila data baharu tersedia. Ini memastikan ramalan kekal tepat dan mencerminkan keadaan sosioekonomi semasa.',

    // Common
    'common.learnMore': 'Ketahui Lebih',
    'common.viewDetails': 'Lihat Butiran',
    'common.explore': 'Terokai',
    'common.recipients': 'Penerima',
    'common.percentage': 'Peratusan',
    'common.district': 'Daerah',
    'common.total': 'Jumlah',
    'common.average': 'Purata',
    'common.year': 'Tahun',
    'common.years': 'tahun',
    'common.total2': 'jumlah',
    'common.projected': 'unjuran',
    'common.dataSource': 'Sumber Data',
    
    // Overview Page Additional
    'overview.recipients': 'Penerima',
    'overview.monthlyRecipients': 'Penerima Bulanan',
    'overview.hoverDetails': 'Letak tetikus pada bar untuk lihat butiran',
    'overview.districtMap': 'Peta Daerah Kedah',
    'overview.clickDistrict': 'Klik pada daerah',
    'overview.interactiveMap': 'Peta interaktif menunjukkan taburan penerima',
    'overview.viewDetails': 'untuk lihat butiran',
    'overview.avgIncome2': 'Purata Pendapatan',
    'overview.avgExpense2': 'Purata Perbelanjaan',
    'overview.unemployedRate': 'Kadar Pengangguran',
    'overview.gap': 'Jurang',
    'overview.month': 'bulan',
    'overview.lowDensity': 'Kepadatan Rendah',
    'overview.highDensity': 'Kepadatan Tinggi',
    
    // Statistics Page Additional
    'stats.recipientsByDistrict': 'Penerima Mengikut Daerah',
    'stats.clickBar': 'Klik pada bar untuk lihat butiran',
    'stats.distributionShare': 'Bahagian Taburan',
    'stats.top6Districts': '6 daerah teratas',
    'stats.districts': 'Daerah',
    'stats.ageDistribution': 'Taburan Umur',
    'stats.recipientsByAge': 'Penerima mengikut kumpulan umur',
    'stats.demographicInsights': 'Pandangan Demografi',
    'stats.female': 'Perempuan',
    'stats.male': 'Lelaki',
    'stats.married': 'Berkahwin',
    'stats.healthy': 'Sihat',
    'stats.averageAge': 'Purata Umur',
    'stats.topDistrict': 'Daerah Teratas',
    
    // Forecast Page Additional
    'forecast.generalForecast': 'Ramalan Umum Berbilang Tahun',
    'forecast.consolidatedProjections': 'Unjuran keluar kemiskinan disatukan (2022-2027)',
    'forecast.totalRecipients': 'Jumlah Penerima',
    'forecast.avgRecipientsYear': 'Purata Penerima/Tahun',
    'forecast.escapeRate': 'Kadar Keluar',
    'forecast.escapeRateTrend': 'Trend Kadar Keluar',
    'forecast.actual': 'Sebenar',
    'forecast.forecastLabel': 'Ramalan',
    'forecast.growth': 'Pertumbuhan',
    'forecast.currentRate': 'Kadar Semasa',
    'forecast.target': 'Sasaran',
    'forecast.projectedGrowth': 'Unjuran Pertumbuhan',
    'forecast.improvingTrend': 'Trend Meningkat',
    'forecast.improvingDesc': 'Kadar keluar meningkat dari 12.3% (2022) kepada 16.2% (2024), peningkatan 31.7%',
    'forecast.threeYearProjection': 'Unjuran 3 Tahun',
    'forecast.projectionDesc': 'Model meramalkan kadar keluar mencapai 24% menjelang 2027 dengan strategi intervensi semasa',
    'forecast.recipientInfo': 'Maklumat Penerima',
    
    // Report Page Additional
    'report.healthStatus': 'Status Kesihatan',
    'report.recipientsByHealth': 'Penerima mengikut keadaan kesihatan',
    'report.maritalStatus': 'Status Perkahwinan',
    'report.distributionByFamily': 'Taburan mengikut status keluarga',
    'report.employmentStatus': 'Status Pekerjaan',
    'report.monthlyExpenses': 'Perbelanjaan Bulanan',
    'report.housingType': 'Jenis Perumahan',
    'report.basedOnHouse': 'Berdasarkan jenis struktur rumah (Batu/Kayu)',
    'report.recipientsByYear': 'Penerima Mengikut Tahun',
    'report.annualDistribution': 'Taburan tahunan (2022-2024)',
    'report.avgYear': 'Purata/Tahun',
    'report.assetOwnership': 'Pemilikan Aset',
    'report.householdItems': 'Barangan isi rumah yang dimiliki oleh penerima',

    // About Page Additional
    'about.researchOverview': 'Gambaran Penyelidikan',
    'about.understandingScope': 'Memahami skop dan objektif projek',
    'about.modelPerformance': 'Prestasi Model',
    'about.comparingAlgorithms': 'Membandingkan algoritma pembelajaran mesin',
    'about.selectedModel': 'Model Dipilih',
    'about.whySVM': 'Mengapa SVM Dipilih',
    'about.keyFeatures': 'Ciri Utama Dianalisis',
    'about.socioeconomicIndicators': '113 penunjuk sosioekonomi merentasi 6 kategori',
    'about.methodologyTitle': 'Metodologi',
    'about.ourProcess': 'Proses penyelidikan kami langkah demi langkah',
    'about.dataCollected': 'Data Dikumpul',
    'about.officialRecords': 'Rekod rasmi penerima zakat dari 2022-2024',
    'about.researchDesc1': 'Projek ini membangunkan',
    'about.mlModel': 'model ramalan berasaskan pembelajaran mesin',
    'about.researchDesc2': 'untuk menilai kebarangkalian penerima zakat keluar dari kemiskinan. Menggunakan data komprehensif daripada',
    'about.asnaf': '(penerima zakat)',
    'about.researchDesc3': 'di Kedah, Malaysia yang dikumpul antara 2022-2024, kami menganalisis',
    'about.researchDesc4': 'untuk meramal potensi keluar dalam tempoh 3 tahun.',
    'about.researchDesc5': 'Model ini membolehkan institusi zakat untuk',
    'about.optimizeResource': 'mengoptimumkan peruntukan sumber',
    'about.researchDesc6': 'dan membangunkan',
    'about.targetedIntervention': 'strategi intervensi bersasar',
    'about.researchDesc7': 'yang disesuaikan dengan profil penerima yang berbeza, memaksimumkan impak sosial pengagihan zakat.',
    'about.svm1.title': 'ROC-AUC Tertinggi (98.96%)',
    'about.svm1.desc': 'Keupayaan unggul untuk membezakan antara penerima yang boleh keluar dari kemiskinan berbanding yang tidak.',
    'about.svm2.title': 'Ketepatan Terbaik (94.73%)',
    'about.svm2.desc': 'Mengatasi semua model lain dalam mengklasifikasikan hasil penerima dengan betul.',
    'about.svm3.title': 'Mengendalikan Dimensi Tinggi',
    'about.svm3.desc': 'Memproses 113 ciri dengan berkesan menggunakan kernel RBF untuk hubungan bukan linear yang kompleks.',
    'about.svm4.title': 'Tahan Overfitting',
    'about.svm4.desc': 'Pengoptimuman berasaskan margin memberikan generalisasi lebih baik pada data yang tidak dilihat.',
    'about.feat.demographics': 'Demografi',
    'about.feat.demographics.desc': 'Umur, jantina, status perkahwinan, tanggungan',
    'about.feat.financial': 'Status Kewangan',
    'about.feat.financial.desc': 'Pendapatan, perbelanjaan, simpanan, hutang',
    'about.feat.employment': 'Pekerjaan',
    'about.feat.employment.desc': 'Jenis pekerjaan, sektor pekerjaan, kemahiran',
    'about.feat.health': 'Kesihatan',
    'about.feat.health.desc': 'Status kesihatan, kecacatan, penyakit kronik',
    'about.feat.assets': 'Aset',
    'about.feat.assets.desc': 'Harta, kenderaan, peralatan yang dimiliki',
    'about.feat.geographic': 'Geografi',
    'about.feat.geographic.desc': 'Daerah, lokasi bandar/luar bandar',
    'about.method1.title': 'Pengumpulan Data',
    'about.method1.desc': 'Mengumpul data komprehensif daripada LZNK mengenai 51,962 penerima di semua 12 daerah di negeri Kedah.',
    'about.method2.title': 'Kejuruteraan Ciri',
    'about.method2.desc': 'Memproses dan merekayasa 113 ciri termasuk nisbah pendapatan, corak perbelanjaan, dan penunjuk risiko.',
    'about.method3.title': 'Latihan Model',
    'about.method3.desc': 'Membandingkan pelbagai algoritma ML: Regresi Logistik, Random Forest, SVM, dan Gradient Boosting.',
    'about.method4.title': 'Pengesahan',
    'about.method4.desc': 'Menggunakan pengesahan silang k-fold berstrata untuk memastikan anggaran prestasi yang kukuh dan boleh dipercayai.',

    // Home Page Additional
    'home.incomeVsExpense': 'Jurang Pendapatan vs Perbelanjaan',
    'home.incomeVsExpense.desc': 'Situasi kewangan bulanan purata penerima',
    'home.income': 'Pendapatan',
    'home.expenses': 'Perbelanjaan',
    'home.gap': 'Jurang',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Initialize from localStorage if available (client-side only)
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('language') as Language;
      if (savedLang && (savedLang === 'en' || savedLang === 'ms')) {
        return savedLang;
      }
    }
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
